### ISSUE TITLE
Batch changes blog post

### ISSUE THREAD

**Issue by jdorfman** [sourcegraph/community#3]
A blog post showing how we use batch changes to add ~100 Apache 2.0 licenses to repos

https://docs.google.com/document/d/1GA5YCb6tcbHvnjmsp2r5GSLLpT02VjYQZXgRljznIKs/edit#

- [x] Graphic (in progress)
- [x] Create PR on About
- [x] Work with content platform on syntax highlighting issue
- [x] Send to Bachi
- [x] Progress?
- [x] Send to TODO group

**Comment by jdorfman** [comment]
Had a call with Daniel, we ran into an issue with the spec not creating a diff/changeset. Recorded the call. Reached out to Malo

**Comment by beyang** [comment]
Do we have a target date?

**Comment by jdorfman** [comment]
@beyang I'm shooting for next week. If anything changes I'll update this issue.

**Comment by jdorfman** [comment]
Going to take a few more days, ran into an unexpected issue.

**Comment by jdorfman** [comment]
Syntax highlighting is not working on embeds 

![Image](https://user-images.githubusercontent.com/398230/175099556-b0eb3b6a-f6a7-41b9-8930-a9d24dcc6348.jpg)

![Image](https://user-images.githubusercontent.com/398230/175099654-3a39a5fd-2d72-425b-a9eb-74b00deea8a5.png)

**Comment by mplacona** [comment]
Heya! Is this fixed now? Where can I check progress?

**Comment by jdorfman** [comment]
https://about.sourcegraph.com/blog/batch-changes-ospo
