### ISSUE TITLE
Slack to Discord

### ISSUE THREAD

**Issue by jdorfman** [sourcegraph/community#6]
* [Google Doc](https://docs.google.com/document/d/1j0OElIVjhA09m8ek47JYQKGCpliEIL-yV8PkajZs0KA/edit)

---

- [ ] Update support
- [ ] Post to #progress

**Comment by beyang** [comment]
@jdorfman is this done?

**Comment by jdorfman** [comment]
@beyang Not yet, shutting Slack down July 1st.

**Comment by jdorfman** [comment]
Current status 

![Image](https://user-images.githubusercontent.com/398230/172492994-fdc3a862-4917-4fd3-bb3c-4eeadfa2adf0.jpg)

**Comment by beyang** [comment]
@jdorfman is this done?

**Comment by jdorfman** [comment]
Not yet. I had a call with Support today and we are looking for a way to
sync Discord with Zendesk the same way Slack does it.

This task will be closed out EOM.

**Comment by beyang** [comment]
@jdorfman can we close this out? I would say we can address support requests ad hoc for now and not worry about Zendesk integration. If it becomes an issue, we can open that as a separate line item
